# docker-compose.yml

version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_CONN_STRING: ${DB_CONN_STRING}
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=space_trouble
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
